import type { FormCodeDocument } from "./types";
import { DEFAULT_SETTINGS } from "./types";

export const JOB_FIELDS_QUICK = ["IT / Software / Tech", "Sales", "BPO / Customer Support"];

export const JOB_FIELDS_MORE = [
  "Marketing",
  "HR",
  "Finance / Accounting",
  "Data Entry",
  "Back Office",
  "Engineering",
  "Healthcare",
  "Teaching",
  "Design / Creative",
];

export const JOB_CITIES_QUICK = ["Nagpur", "Pune", "Mumbai", "Anywhere"];

export const JOB_CITIES_MORE = [
  "Work From Home",
  "Nashik",
  "Aurangabad",
  "Amravati",
  "Kolhapur",
  "Solapur",
  "Nanded",
  "Akola",
  "Jalgaon",
  "Wardha",
  "Chandrapur",
  "Latur",
  "Ahmedabad",
  "Indore",
  "Bhopal",
  "Hyderabad",
  "Bengaluru",
  "Delhi NCR",
  "Chennai",
  "Kolkata",
  "Jaipur",
  "Surat",
  "Lucknow",
];

export const JOB_FIELDS = [...JOB_FIELDS_QUICK, ...JOB_FIELDS_MORE];
export const JOB_CITIES = [...JOB_CITIES_QUICK, ...JOB_CITIES_MORE];
export const CITIES_MORE = JOB_CITIES_MORE;

/** The live CareerSparks intake form. */
export const JOB_REQUIREMENT_FORM: FormCodeDocument = {
  title: "Job Requirement Form",
  description: "Quick form. We match you and WhatsApp openings.",
  mode: "conversational",
  category: "application",
  settings: {
    ...DEFAULT_SETTINGS,
    thankYou: "Thank you. CareerSparks will WhatsApp you when a matching role is in.",
    whatsappMessage: "Job requirement form — 1 minute:",
    allowMultiple: false,
    sendThankYouEmail: false,
    collectContact: true,
    notifyAdmin: true,
  },
  questions: [
    { id: "q_name", type: "short_text", title: "Full Name", required: true },
    {
      id: "q_phone",
      type: "phone",
      title: "WhatsApp Number",
      required: true,
      description: "Exactly 10 digits. Indian mobile only.",
    },
    {
      id: "q_email",
      type: "email",
      title: "Email",
      required: true,
      description: "Use a real inbox — Gmail, Outlook or company mail.",
    },
    {
      id: "q_field",
      type: "multiple",
      title: "Aap kis field mein job chahte hain?",
      description: "IT, Sales, BPO tap karo. Baaki list se. Ek se zyada chalega.",
      required: true,
      options: JOB_FIELDS_QUICK,
      moreOptions: JOB_FIELDS_MORE,
    },
    {
      id: "q_exp",
      type: "single",
      title: "Aap Fresher hain ya Experienced?",
      required: true,
      options: ["Fresher", "Experienced"],
    },
    {
      id: "q_years",
      type: "single",
      title: "Kitne saal ka experience?",
      required: true,
      options: ["Less than 1 year", "1–3 years", "3–5 years", "5+ years"],
      showIf: { questionId: "q_exp", equals: "Experienced" },
    },
    {
      id: "q_city",
      type: "single",
      title: "Aapko job kahan chahiye?",
      description: "Nagpur, Pune, Mumbai ya Anywhere. Baaki city list se.",
      required: true,
      options: JOB_CITIES_QUICK,
      moreOptions: JOB_CITIES_MORE,
    },
    {
      id: "q_type",
      type: "single",
      title: "Aap kis type ki job chahte hain?",
      required: true,
      options: ["Full Time", "Part Time", "Internship", "Any"],
    },
  ],
};

export const FORM_TEMPLATES: FormCodeDocument[] = [
  JOB_REQUIREMENT_FORM,
  {
    title: "Candidate Screening Quiz",
    description:
      "A short aptitude screen. Answer carefully — this is scored. Pass mark 60%.",
    mode: "conversational",
    category: "screening",
    settings: {
      ...DEFAULT_SETTINGS,
      quizMode: true,
      passPercent: 60,
      thankYou: "Quiz submitted. Your score is shown below. CareerSparks will contact shortlisted candidates.",
      whatsappMessage: "CareerSparks screening quiz — 8 questions, auto-scored:",
    },
    questions: [
      { id: "q_name", type: "short_text", title: "Full name", required: true },
      { id: "q_email", type: "email", title: "Email", required: true },
      { id: "q_phone", type: "phone", title: "WhatsApp number", required: true },
      {
        id: "q1",
        type: "single",
        title: "A shop offers 20% off on ₹2,500. What is the selling price?",
        required: true,
        options: ["₹1,800", "₹2,000", "₹2,200", "₹2,300"],
        correct: "₹2,000",
        points: 10,
      },
      {
        id: "q2",
        type: "single",
        title: "If 6 people finish a job in 8 days, 8 people will finish it in:",
        required: true,
        options: ["4 days", "6 days", "8 days", "12 days"],
        correct: "6 days",
        points: 10,
      },
      {
        id: "q3",
        type: "single",
        title: "Choose the correctly spelled word.",
        required: true,
        options: ["Recieve", "Receive", "Receeve", "Receve"],
        correct: "Receive",
        points: 10,
      },
      {
        id: "q4",
        type: "single",
        title: "A client is unhappy with a delay. Best first response?",
        required: true,
        options: [
          "Blame the team",
          "Ignore until they cool down",
          "Acknowledge, share a timeline, follow up",
          "Offer a discount immediately",
        ],
        correct: "Acknowledge, share a timeline, follow up",
        points: 15,
      },
      {
        id: "q5",
        type: "single",
        title: "Which number comes next: 2, 6, 12, 20, 30, ?",
        required: true,
        options: ["36", "40", "42", "44"],
        correct: "42",
        points: 10,
      },
      {
        id: "q6",
        type: "yes_no",
        title: "Are you comfortable with field / client-facing work?",
        required: true,
        options: ["Yes", "No"],
        correct: "Yes",
        points: 5,
      },
      {
        id: "q7",
        type: "rating",
        title: "Rate your spoken English (1 = basic, 5 = fluent)",
        required: true,
        min: 1,
        max: 5,
      },
      {
        id: "q8",
        type: "long_text",
        title: "In 3 lines: a time you handled pressure at work or college.",
        required: true,
      },
    ],
  },
  {
    title: "Client Hiring Request",
    description: "Tell CareerSparks who you need. We shortlist matching candidates from our pool.",
    mode: "classic",
    category: "client",
    settings: {
      ...DEFAULT_SETTINGS,
      thankYou: "Requirement received. A consultant will call you within one business day.",
      whatsappMessage: "Need hiring support? Share your requirement with CareerSparks:",
    },
    questions: [
      { id: "q_company", type: "short_text", title: "Company name", required: true },
      { id: "q_name", type: "short_text", title: "Your name", required: true },
      { id: "q_email", type: "email", title: "Work email", required: true },
      { id: "q_phone", type: "phone", title: "Phone", required: true },
      { id: "q_role", type: "short_text", title: "Role to hire", required: true },
      {
        id: "q_openings",
        type: "number",
        title: "Number of openings",
        required: true,
        min: 1,
        max: 500,
      },
      {
        id: "q_city",
        type: "short_text",
        title: "Job location",
        required: true,
      },
      {
        id: "q_type",
        type: "single",
        title: "Employment type",
        required: true,
        options: ["Full-time", "Contract", "Internship", "Walk-in drive"],
      },
      { id: "q_budget", type: "short_text", title: "Salary budget / CTC range", required: true },
      { id: "q_jd", type: "long_text", title: "Job description / must-have skills", required: true },
      {
        id: "q_when",
        type: "single",
        title: "When do you want to close this?",
        required: true,
        options: ["This week", "This month", "Flexible"],
      },
    ],
  },
  {
    title: "Interview Feedback",
    description: "Recruiter or panel notes after a candidate interview.",
    mode: "classic",
    category: "feedback",
    settings: {
      ...DEFAULT_SETTINGS,
      thankYou: "Feedback saved. The hiring team can see this on the candidate record.",
      whatsappMessage: "Share interview feedback for today’s CareerSparks candidate:",
    },
    questions: [
      { id: "q_cand", type: "short_text", title: "Candidate name", required: true },
      { id: "q_role", type: "short_text", title: "Role interviewed for", required: true },
      { id: "q_panel", type: "short_text", title: "Interviewer name", required: true },
      { id: "q_date", type: "date", title: "Interview date", required: true },
      {
        id: "q_comm",
        type: "rating",
        title: "Communication",
        required: true,
        min: 1,
        max: 5,
      },
      {
        id: "q_skill",
        type: "rating",
        title: "Role skills",
        required: true,
        min: 1,
        max: 5,
      },
      {
        id: "q_cult",
        type: "rating",
        title: "Culture fit",
        required: true,
        min: 1,
        max: 5,
      },
      {
        id: "q_rec",
        type: "single",
        title: "Recommendation",
        required: true,
        options: ["Strong hire", "Hire", "Hold", "Reject"],
      },
      { id: "q_notes", type: "long_text", title: "Notes for the client / next round", required: false },
    ],
  },
  {
    title: "Walk-in / Job Fair Registration",
    description: "Register for today’s CareerSparks walk-in drive. Keep this open at the desk.",
    mode: "conversational",
    category: "event",
    settings: {
      ...DEFAULT_SETTINGS,
      thankYou: "You are registered. Please wait for your token — our desk will call your name.",
      whatsappMessage: "Register for the CareerSparks walk-in drive:",
    },
    questions: [
      { id: "q_name", type: "short_text", title: "Full name", required: true },
      { id: "q_phone", type: "phone", title: "WhatsApp number", required: true },
      { id: "q_email", type: "email", title: "Email", required: false },
      {
        id: "q_role",
        type: "single",
        title: "Which counter?",
        required: true,
        options: ["Sales", "Accounts", "IT / Software", "BPO / Support", "Any open role"],
      },
      {
        id: "q_exp",
        type: "single",
        title: "Experience",
        required: true,
        options: ["Fresher", "Experienced"],
      },
      { id: "q_city", type: "short_text", title: "Coming from (area / city)", required: true },
      { id: "q_resume", type: "file", title: "Resume (optional if you brought a printout)", required: false },
    ],
  },
  {
    title: "Community Pulse — Are you looking?",
    description:
      "A 60-second pulse for the CareerSparks WhatsApp community. Helps us match the right jobs to you.",
    mode: "conversational",
    category: "pulse",
    settings: {
      ...DEFAULT_SETTINGS,
      thankYou: "Got it. We will share roles that match what you selected.",
      whatsappMessage: "CareerSparks community pulse — 4 taps, helps us send the right jobs:",
    },
    questions: [
      {
        id: "q_status",
        type: "single",
        title: "Are you looking for a job right now?",
        required: true,
        options: ["Actively looking", "Open to offers", "Not looking", "Hiring for my company"],
      },
      {
        id: "q_func",
        type: "multiple",
        title: "Functions you want roles in",
        required: true,
        options: ["Sales", "Marketing", "Accounts", "HR", "IT", "Operations", "Freshers / any"],
        showIf: { questionId: "q_status", equals: "Actively looking" },
      },
      {
        id: "q_city",
        type: "short_text",
        title: "Preferred city",
        required: true,
      },
      {
        id: "q_notice",
        type: "single",
        title: "How soon can you join?",
        required: true,
        options: ["Immediate", "15 days", "30 days", "60 days+"],
      },
      { id: "q_phone", type: "phone", title: "WhatsApp number", required: true },
      { id: "q_name", type: "short_text", title: "Name", required: false },
    ],
  },
];

export function templateByCategory(category: string): FormCodeDocument | undefined {
  return FORM_TEMPLATES.find((t) => t.category === category);
}
