/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AdminFormsIndexRouteImport } from './routes/admin.forms.index'
import { Route as AdminFormsFormIdRouteImport } from './routes/admin.forms.$formId'
import { Route as AdminFormsNewRouteImport } from './routes/admin.forms.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminFormsFormIdIndexRouteImport } from './routes/admin.forms.$formId.index'
import { Route as AdminFormsFormIdAnalyticsRouteImport } from './routes/admin.forms.$formId.analytics'
import { Route as AdminFormsFormIdResponsesRouteImport } from './routes/admin.forms.$formId.responses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsIndexRoute = AdminFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminFormsFormIdRoute = AdminFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminFormsNewRoute = AdminFormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFormsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsFormIdIndexRoute = AdminFormsFormIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFormsFormIdRoute,
} as any)
const AdminFormsFormIdAnalyticsRoute =
  AdminFormsFormIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminFormsFormIdRoute,
  } as any)
const AdminFormsFormIdResponsesRoute =
  AdminFormsFormIdResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => AdminFormsFormIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/setup': typeof ApiSetupRoute
  '/f/$slug': typeof FSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRouteWithChildren
  '/admin/forms/new': typeof AdminFormsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/forms/$formId/analytics': typeof AdminFormsFormIdAnalyticsRoute
  '/admin/forms/$formId/responses': typeof AdminFormsFormIdResponsesRoute
  '/admin/forms/$formId/': typeof AdminFormsFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/setup': typeof ApiSetupRoute
  '/f/$slug': typeof FSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forms/new': typeof AdminFormsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/forms': typeof AdminFormsIndexRoute
  '/admin/forms/$formId/analytics': typeof AdminFormsFormIdAnalyticsRoute
  '/admin/forms/$formId/responses': typeof AdminFormsFormIdResponsesRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/setup': typeof ApiSetupRoute
  '/f/$slug': typeof FSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRouteWithChildren
  '/admin/forms/new': typeof AdminFormsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/forms/$formId/analytics': typeof AdminFormsFormIdAnalyticsRoute
  '/admin/forms/$formId/responses': typeof AdminFormsFormIdResponsesRoute
  '/admin/forms/$formId/': typeof AdminFormsFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/install'
    | '/login'
    | '/admin/forms'
    | '/admin/inbox'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/templates'
    | '/api/setup'
    | '/f/$slug'
    | '/admin/'
    | '/admin/forms/$formId'
    | '/admin/forms/new'
    | '/api/auth/$'
    | '/admin/forms/'
    | '/admin/forms/$formId/analytics'
    | '/admin/forms/$formId/responses'
    | '/admin/forms/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/login'
    | '/admin/inbox'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/templates'
    | '/api/setup'
    | '/f/$slug'
    | '/admin'
    | '/admin/forms/new'
    | '/api/auth/$'
    | '/admin/forms'
    | '/admin/forms/$formId/analytics'
    | '/admin/forms/$formId/responses'
    | '/admin/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/install'
    | '/login'
    | '/admin/forms'
    | '/admin/inbox'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/templates'
    | '/api/setup'
    | '/f/$slug'
    | '/admin/'
    | '/admin/forms/$formId'
    | '/admin/forms/new'
    | '/api/auth/$'
    | '/admin/forms/'
    | '/admin/forms/$formId/analytics'
    | '/admin/forms/$formId/responses'
    | '/admin/forms/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  ApiSetupRoute: typeof ApiSetupRoute
  FSlugRoute: typeof FSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms/': {
      id: '/admin/forms/'
      path: '/'
      fullPath: '/admin/forms/'
      preLoaderRoute: typeof AdminFormsIndexRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/forms/$formId': {
      id: '/admin/forms/$formId'
      path: '/$formId'
      fullPath: '/admin/forms/$formId'
      preLoaderRoute: typeof AdminFormsFormIdRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/forms/new': {
      id: '/admin/forms/new'
      path: '/new'
      fullPath: '/admin/forms/new'
      preLoaderRoute: typeof AdminFormsNewRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms/$formId/': {
      id: '/admin/forms/$formId/'
      path: '/'
      fullPath: '/admin/forms/$formId/'
      preLoaderRoute: typeof AdminFormsFormIdIndexRouteImport
      parentRoute: typeof AdminFormsFormIdRoute
    }
    '/admin/forms/$formId/analytics': {
      id: '/admin/forms/$formId/analytics'
      path: '/analytics'
      fullPath: '/admin/forms/$formId/analytics'
      preLoaderRoute: typeof AdminFormsFormIdAnalyticsRouteImport
      parentRoute: typeof AdminFormsFormIdRoute
    }
    '/admin/forms/$formId/responses': {
      id: '/admin/forms/$formId/responses'
      path: '/responses'
      fullPath: '/admin/forms/$formId/responses'
      preLoaderRoute: typeof AdminFormsFormIdResponsesRouteImport
      parentRoute: typeof AdminFormsFormIdRoute
    }
  }
}

interface AdminFormsFormIdRouteChildren {
  AdminFormsFormIdAnalyticsRoute: typeof AdminFormsFormIdAnalyticsRoute
  AdminFormsFormIdResponsesRoute: typeof AdminFormsFormIdResponsesRoute
  AdminFormsFormIdIndexRoute: typeof AdminFormsFormIdIndexRoute
}

const AdminFormsFormIdRouteChildren: AdminFormsFormIdRouteChildren = {
  AdminFormsFormIdAnalyticsRoute: AdminFormsFormIdAnalyticsRoute,
  AdminFormsFormIdResponsesRoute: AdminFormsFormIdResponsesRoute,
  AdminFormsFormIdIndexRoute: AdminFormsFormIdIndexRoute,
}

const AdminFormsFormIdRouteWithChildren =
  AdminFormsFormIdRoute._addFileChildren(AdminFormsFormIdRouteChildren)

interface AdminFormsRouteChildren {
  AdminFormsFormIdRoute: typeof AdminFormsFormIdRouteWithChildren
  AdminFormsNewRoute: typeof AdminFormsNewRoute
  AdminFormsIndexRoute: typeof AdminFormsIndexRoute
}

const AdminFormsRouteChildren: AdminFormsRouteChildren = {
  AdminFormsFormIdRoute: AdminFormsFormIdRouteWithChildren,
  AdminFormsNewRoute: AdminFormsNewRoute,
  AdminFormsIndexRoute: AdminFormsIndexRoute,
}

const AdminFormsRouteWithChildren = AdminFormsRoute._addFileChildren(
  AdminFormsRouteChildren,
)

interface AdminRouteChildren {
  AdminFormsRoute: typeof AdminFormsRouteWithChildren
  AdminInboxRoute: typeof AdminInboxRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFormsRoute: AdminFormsRouteWithChildren,
  AdminInboxRoute: AdminInboxRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  ApiSetupRoute: ApiSetupRoute,
  FSlugRoute: FSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
